name: linked_lights
description: A Flutter puzzle game
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: ArchitypeRenner
    fonts:
    - asset: assets/fonts/ArchitypeRenner-Bold.otf
      weight: 700
    - asset: assets/fonts/ArchitypeRenner-Demi.otf
      weight: 600
    - asset: assets/fonts/ArchitypeRenner-Medium.otf
      weight: 500
    - asset: assets/fonts/ArchitypeRenner-Regular.otf
      weight: 400
  - family: LiliIcon
    fonts:
    - asset: assets/icons/LiliIcon.ttf
